[package]
name = "rust-nethuns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"

[build-dependencies]
bindgen = { version = "0.66.1", features = ["experimental"] }

[dev-dependencies]
bus = "2.4.0"
ctrlc = "3.4.0"
pico-args = "0.5.0"
