[package]
name = "nethuns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
c_netmap_wrapper = { version = "0.1.0", path = "./lib/netmap", optional = true }
cfg-if = "1.0.0"
derivative = "2.2.0"
derive-new = "0.5.9"
derive_builder = "0.12.0"
errno = "0.3.1"
etherparse = "0.13.0"
is_trait = "0.1.4"
libc = "0.2.147"
num-traits = "0.2.16"
once_cell = "1.18.0"
rustix = "0.38.4"
thiserror = "1.0.44"


[build-dependencies]
bindgen = { version = "0.66.1", features = ["experimental"] }
cfg-if = "1.0.0"


[dev-dependencies]


[features]
default = ["netmap", "libc/extra_traits", "rustix/net"] # FIXME remove netmap from default features
netmap = ["dep:c_netmap_wrapper"]
libpcap = []
xdp = []
tpacket_v3 = []
